Fix onsite create user
Onsite user creation was erroring with
```
TypeError: _create_user() got multiple values for keyword argument 'is_superuser'
```
(see https://sentry.mit.edu/esp/esp-website/issues/230/).  I'm not entirely
sure why, but specifying `is_staff` and `is_superuser` is unnecessary, since
they both default to `False` anyway, so we can just leave it out, and things
work fine.

(cherry picked and cleaned up a bit from commit b0ac8af59 in mit-prod)