Fix bug causing a hang on studentreg.
Actually, this is already fixed [1]. But since Document.get_completed
really expects a DataTree, not a bound method, this patch helps to
establish correct behavior anyway. Here's the explanation:

  * The main student registration page calls isCompleted on each
    program module. This one calls Document.get_completed, a cache
    function that constructs its cache keys from its arguments.
    The __repr__ of the program_anchor_cached method is big enough
    to bump the resulting key over 250 characters in length.

  * Following our slightly incorrect [1] MAX_KEY_LENGTH, we cut this
    down to exactly 251 chars. Normally this would get a ClientError:
        >>> from esp.utils.pylibcmd import CacheClass
        >>> c = CacheClass('localhost:11211', {'timeout': 300})
        >>> c.get_many(['x', 'x'*251])
        ClientError: error 9 from memcached_fetch: CLIENT ERROR

  * However, in the right conditions, something gets stuck [2]:
        >>> c.set('x', 1)
        >>> c.get_many(['x', 'x'*251])
    Memcached first sends the result for 'x' before it sees 'x'*251
    and complains with "CLIENT_ERROR bad command line format". For
    whatever reason, pylibmc is unprepared for this, and get_many
    never returns. (I would surmise that pylibmc is waiting for some
    end-of-conversation signal that never gets sent because memcached
    is too busy being offended at a 251-character key.)

  * In the end I get a hung shell that I have to escape by repeatedly
    hitting Ctrl-C; and SATPrep students spend forever waiting for a
    studentreg page that will never load.

Footnotes:
[1] See previous commit, 5c69b90ed223c883286db7555e9c50185fc5127c
    ("Cache: Bump MAX_KEY_LENGTH down to 250.")
[2] It may be illuminating to try calling get_many with slightly
    different input; for instance, switching the order of 'x' and
    'x'*251 results in a ClientError instead of a hang.